name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  checks:   write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create & activate virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies & CLI
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run pre-commit checks
        run: |
          source .venv/bin/activate
          pre-commit run --all-files

      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest --junitxml=pytest-results.xml

      - name: Publish Pytest results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/pytest-results.xml'
          check_name: Pytest Tests

  promptguard-ci:
    needs: lint-and-test
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PERSPECTIVE_API_KEY: ${{ secrets.PERSPECTIVE_API_KEY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create & activate virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install PromptGuard CLI
        run: |
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e .

      - name: Run PromptGuard tests
        run: |
          source .venv/bin/activate
          promptguard test examples/hello.yml \
            --junit-output promptguard-results.xml

      - name: Publish PromptGuard results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/promptguard-results.xml'
          check_name: PromptGuard CI
